_target_: src.scheduler.ReduceLROnPlateauScheduler
mode: 'min'
factor: 0.7           # Более плавное уменьшение (в 1.43 раза)
patience: 5          # Больше терпения
threshold: 0.0001     # Более чувствительный
min_lr: 1e-7